/* GENERATED by scripts/session2/export_site.py from the Session 2 content modules — do not edit by hand.
 * The same source builds the slides and the Word documents, so the website cannot drift from them.
 * All Irish is grammar-checked but not yet native-speaker validated (see the QA report). */
export const S2 = {
  "FAILURES": [
    {
      "id": "f1",
      "name": {
        "ga": "‘Hallucination’ — foinse nó sonra cumtha",
        "en": "“Hallucination” — a made-up source or detail"
      },
      "looks": {
        "ga": "Luann sé tuarascáil nó alt nach bhfuil ann.",
        "en": "It cites a report or article that does not exist."
      },
      "check": {
        "ga": "Faigh an fhoinse féin.",
        "en": "Find the source itself."
      }
    },
    {
      "id": "f2",
      "name": {
        "ga": "Fíricí míchearta",
        "en": "Incorrect facts"
      },
      "looks": {
        "ga": "Dáta, uimhir nó ainm atá mícheart.",
        "en": "A date, number or name that is wrong."
      },
      "check": {
        "ga": "Seiceáil uimhreacha, dátaí agus ainmneacha.",
        "en": "Check numbers, dates and names."
      }
    },
    {
      "id": "f3",
      "name": {
        "ga": "Freagraí róchinnte",
        "en": "Overconfident answers"
      },
      "looks": {
        "ga": "Ton cinnte ar rud nach bhfuil cinnte.",
        "en": "A confident tone about something uncertain."
      },
      "check": {
        "ga": "Iarr air an fhoinse a lua.",
        "en": "Ask it to quote its source."
      }
    },
    {
      "id": "f4",
      "name": {
        "ga": "Droch-Ghaeilge",
        "en": "Poor Irish"
      },
      "looks": {
        "ga": "Gramadach mhícheart, nó Gaeilge atá cosúil le Béarla aistrithe focal ar fhocal.",
        "en": "Wrong grammar, or Irish that reads like word-for-word English."
      },
      "check": {
        "ga": "Ní mór do dhuine a bhfuil Gaeilge mhaith aige nó aici é a léamh.",
        "en": "A competent Irish speaker must read it."
      }
    },
    {
      "id": "f5",
      "name": {
        "ga": "Ton mícheart",
        "en": "Wrong tone"
      },
      "looks": {
        "ga": "An iomarca foirmiúlachta, nó gan a dhóthain foirmiúlachta, don lucht féachana.",
        "en": "Too formal, or too casual, for the audience."
      },
      "check": {
        "ga": "Léigh os ard é. An gcloiseann tú muid ann?",
        "en": "Read it aloud. Does it sound like us?"
      }
    },
    {
      "id": "f6",
      "name": {
        "ga": "Faisnéis chumtha",
        "en": "Invented information"
      },
      "looks": {
        "ga": "Sonra nár tugadh dó: praghas, dáta, duais.",
        "en": "A detail it was never given: a price, a date, an award."
      },
      "check": {
        "ga": "Cuir marc ar gach sonra nár thug tú dó.",
        "en": "Mark every detail you did not give it."
      }
    },
    {
      "id": "f7",
      "name": {
        "ga": "Comhthéacs ar iarraidh",
        "en": "Missing context"
      },
      "looks": {
        "ga": "Freagra ginearálta, mar níor inis tú dó cé atá ag léamh.",
        "en": "A generic answer, because you never told it who is reading."
      },
      "check": {
        "ga": "Inis dó cé atá ag léamh, cén cuspóir atá leis, agus cad iad na fíricí.",
        "en": "Tell it the reader, the purpose and the facts."
      }
    },
    {
      "id": "f8",
      "name": {
        "ga": "Ábhair imní faoin bpríobháideacht",
        "en": "Privacy concerns"
      },
      "looks": {
        "ga": "Sonraí pearsanta nó rúnda curtha isteach in uirlis phoiblí.",
        "en": "Personal or confidential data put into a public tool."
      },
      "check": {
        "ga": "An tástáil STOP, sula gcuireann tú isteach é.",
        "en": "The STOP test, before you put it in."
      }
    },
    {
      "id": "f9",
      "name": {
        "ga": "An tasc a thuiscint go mícheart",
        "en": "Misunderstanding the task"
      },
      "looks": {
        "ga": "Freagra maith ar cheist nár chuir tú.",
        "en": "A good answer to a question you did not ask."
      },
      "check": {
        "ga": "Iarr air an tasc a athrá ina fhocail féin.",
        "en": "Ask it to restate the task in its own words."
      }
    }
  ],
  "FAILURE_SORT": {
    "steps": [
      {
        "min": 3,
        "what": {
          "ga": "Naoi gcineál teipe: léigh iad ar an mballa.",
          "en": "Nine kinds of failure: read them on the wall."
        }
      },
      {
        "min": 10,
        "what": {
          "ga": "I ngrúpaí de thriúr: cuir do theip fhíor féin faoin gcineál ceart. Roghnaigh na trí cinn is coitianta.",
          "en": "In groups of three: place your own real failure under the right kind. Choose the three most common."
        }
      },
      {
        "min": 5,
        "what": {
          "ga": "Do gach ceann: cén tseiceáil a d’fhéadfadh é a ghabháil?",
          "en": "For each: which check would have caught it?"
        }
      },
      {
        "min": 2,
        "what": {
          "ga": "Achoimre: ní theipeann ach cúpla rud, agus ní gá ach cúpla nós chun iad a ghabháil.",
          "en": "Wrap-up: only a few things go wrong, and only a few habits catch them."
        }
      }
    ],
    "note": {
      "ga": "Ná déan Seisiún 1 a athrá. Úsáid do chásanna féin.",
      "en": "Do not repeat Session 1. Use your own cases."
    }
  },
  "FINAL_LABELS": {
    "go": {
      "ga": "Ar aghaidh",
      "en": "Go"
    },
    "fix": {
      "ga": "Ceartaigh ar dtús",
      "en": "Fix first"
    },
    "stop": {
      "ga": "Stop",
      "en": "Stop"
    }
  },
  "LEVEL_LABELS": {
    "green": {
      "ga": "Glas — ceart go leor",
      "en": "Green — fine to use"
    },
    "amber": {
      "ga": "Ómra — ceartaigh ar dtús nó faigh cead",
      "en": "Amber — fix first, or get permission"
    },
    "red": {
      "ga": "Dearg — ná cuir isteach",
      "en": "Red — do not enter"
    }
  },
  "MAKE_SAFE": {
    "before": {
      "ga": "A chara, d’ordaigh mé cóta an 3 Meán Fómhair (uimhir ordaithe 4471) agus níor tháinig sé fós. Is mise Seán Sampla, 12 Bóthar na Trá. Cuir glaoch orm ar 087 000 0000.",
      "en": "Dear sir/madam, I ordered a coat on 3 September (order number 4471) and it has not arrived. I am Seán Sampla, 12 Bóthar na Trá. Please ring me on 087 000 0000."
    },
    "after": {
      "ga": "A chara, d’ordaigh mé cóta an [dáta] (uimhir ordaithe [uimhir]) agus níor tháinig sé fós. Déan teagmháil liom, le do thoil.",
      "en": "Dear sir/madam, I ordered a coat on [date] (order number [number]) and it has not arrived. Please get in touch."
    },
    "task": {
      "ga": "Anaithnidigh an chasaoid seo. Coinnigh an t-ábhar; bain gach sonra a d’fhéadfadh duine a aithint.",
      "en": "Anonymise this complaint. Keep the substance; remove every detail that could identify a person."
    },
    "note": {
      "ga": "Sampla ficseanúil. Ní bhaineann na sonraí le duine ar bith.",
      "en": "Fictional example. The details belong to nobody."
    }
  },
  "META": {
    "id": "s2",
    "title": {
      "ga": "AI Freagrach agus AI don Ghnó Laethúil",
      "en": "Responsible AI and AI for Everyday Business"
    },
    "strapline": {
      "ga": "Ná bíodh muinín agat as rud nár sheiceáil tú.",
      "en": "Don’t trust what you haven’t checked."
    },
    "question": {
      "ga": "Conas is féidir liom AI a úsáid go táirgiúil gan smacht a chailleadh?",
      "en": "How can I use AI productively without losing control?"
    },
    "session": {
      "ga": "Seisiún 2",
      "en": "Session 2"
    },
    "date": {
      "ga": "Dé Luain, 28 Meán Fómhair 2026",
      "en": "Monday 28 September 2026"
    },
    "time": "10:00–13:00",
    "venue": "Campas Íosagáin",
    "notLegal": {
      "ga": "Treoir oideachasúil — ní comhairle dlí í.",
      "en": "Educational guidance — not legal advice."
    },
    "fictionLabel": {
      "ga": "Sampla oiliúna ficseanúil — le haghaidh oiliúna amháin",
      "en": "FICTIONAL TRAINING EXAMPLE – FOR TRAINING ONLY"
    },
    "durationLabel": {
      "ga": "Leathlá · 10:00–13:00",
      "en": "Half day · 10:00–13:00"
    }
  },
  "PRINCIPLE": [
    {
      "ga": "Is féidir le AI dréacht a scríobh.",
      "en": "AI can draft."
    },
    {
      "ga": "Is féidir le AI athbhreithniú a dhéanamh.",
      "en": "AI can review."
    },
    {
      "ga": "Is féidir le AI moltaí a thabhairt.",
      "en": "AI can suggest."
    },
    {
      "ga": "Ní hé AI a cheadaíonn.",
      "en": "AI does not approve."
    }
  ],
  "PRIVACY_CARDS": [
    {
      "id": "g1",
      "level": "green",
      "text": {
        "ga": "Nuachtlitir d’eagraíochta féin a foilsíodh cheana",
        "en": "Your organisation’s own newsletter, already published"
      },
      "why": {
        "ga": "Poiblí cheana.",
        "en": "Already public."
      }
    },
    {
      "id": "g2",
      "level": "green",
      "text": {
        "ga": "Glaoch poiblí ar mhaoiniú, ón láithreán oifigiúil",
        "en": "A public funding call from the official website"
      },
      "why": {
        "ga": "Poiblí. Seiceáil an achoimre in aghaidh na foinse.",
        "en": "Public. Check the summary against the source."
      }
    },
    {
      "id": "g3",
      "level": "green",
      "text": {
        "ga": "Ceist ghinearálta: “Mol cúig líne ábhair do nuachtlitir faoi aonach ceardaíochta.”",
        "en": "A general question: “Suggest five subject lines for a craft-fair newsletter.”"
      },
      "why": {
        "ga": "Gan sonraí pearsanta ná rúnda.",
        "en": "No personal or confidential data."
      }
    },
    {
      "id": "g4",
      "level": "green",
      "text": {
        "ga": "Sampla ficseanúil a chum tú don oiliúint",
        "en": "A fictional example you made up for training"
      },
      "why": {
        "ga": "Ficseanúil: ní bhaineann sé le duine ar bith.",
        "en": "Fictional: it belongs to nobody."
      }
    },
    {
      "id": "a1",
      "level": "amber",
      "text": {
        "ga": "Freagraí suirbhé a bhfuil ainmneacha fós orthu",
        "en": "Survey responses that still include names"
      },
      "why": {
        "ga": "Bain na hainmneacha amach ar dtús.",
        "en": "Remove the names first."
      }
    },
    {
      "id": "a2",
      "level": "amber",
      "text": {
        "ga": "Casaoid ó chustaiméir le hainm agus seoladh",
        "en": "A customer complaint with a name and address"
      },
      "why": {
        "ga": "Anaithnidigh é: bain ainm, seoladh agus uimhir ordaithe.",
        "en": "Anonymise it: remove name, address and order number."
      }
    },
    {
      "id": "a3",
      "level": "amber",
      "text": {
        "ga": "Do thogra maoinithe nár cuireadh isteach fós",
        "en": "Your funding proposal, not yet submitted"
      },
      "why": {
        "ga": "Íogair ó thaobh na tráchtála de. Fág sonraí amach nó faigh cead.",
        "en": "Commercially sensitive. Leave details out or get permission."
      }
    },
    {
      "id": "a4",
      "level": "amber",
      "text": {
        "ga": "Luachan ó sholáthraí, le praghsanna",
        "en": "A supplier’s quote, with prices"
      },
      "why": {
        "ga": "Faigh cead, nó bain na praghsanna amach.",
        "en": "Get permission, or remove the prices."
      }
    },
    {
      "id": "r1",
      "level": "red",
      "text": {
        "ga": "Miontuairiscí cruinnithe boird atá marcáilte ‘Rúnda’",
        "en": "Board meeting minutes marked “Confidential”"
      },
      "why": {
        "ga": "Rúnda. Ná cuir isteach in uirlis phoiblí iad.",
        "en": "Confidential. Not in a public tool."
      }
    },
    {
      "id": "r2",
      "level": "red",
      "text": {
        "ga": "CV nó athbhreithniú feidhmíochta comhghleacaí",
        "en": "A colleague’s CV or performance review"
      },
      "why": {
        "ga": "Pearsanta agus rúnda araon.",
        "en": "Both personal and confidential."
      }
    },
    {
      "id": "r3",
      "level": "red",
      "text": {
        "ga": "Liosta custaiméirí le seoltaí ríomhphoist agus uimhreacha gutháin",
        "en": "A customer list with email addresses and phone numbers"
      },
      "why": {
        "ga": "Sonraí pearsanta ar mhórscála.",
        "en": "Personal data at scale."
      }
    },
    {
      "id": "r4",
      "level": "red",
      "text": {
        "ga": "Pasfhocail nó dintiúir",
        "en": "Passwords or credentials"
      },
      "why": {
        "ga": "Ná cuir isteach riamh.",
        "en": "Never enter them."
      }
    }
  ],
  "PRIVACY_KEY": {
    "ga": "Ní hionann rúnda agus pearsanta, agus ní hionann ceachtar acu agus poiblí.",
    "en": "Confidential is not the same as personal, and neither is the same as public."
  },
  "PRIVACY_TYPES": [
    {
      "id": "personal",
      "name": {
        "ga": "Sonraí pearsanta",
        "en": "Personal data"
      },
      "def": {
        "ga": "Aon fhaisnéis a bhaineann le duine beo atá sainaitheanta nó is féidir a shainaithint: ainm, seoladh, uimhir ghutháin, grianghraf.",
        "en": "Any information about an identified or identifiable living person: a name, address, phone number, photograph."
      }
    },
    {
      "id": "confidential",
      "name": {
        "ga": "Faisnéis rúnda",
        "en": "Confidential information"
      },
      "def": {
        "ga": "Faisnéis nach bhfuil poiblí, agus a bhfuiltear ag súil go gcoinneofar príobháideach í: conarthaí, miontuairiscí cruinnithe, praghsanna neamhfhoilsithe.",
        "en": "Information that is not public and that people expect you to keep private: contracts, meeting minutes, unpublished prices."
      }
    },
    {
      "id": "public",
      "name": {
        "ga": "Faisnéis phoiblí",
        "en": "Public information"
      },
      "def": {
        "ga": "Faisnéis a d’fhoilsigh a húinéir cheana don saol mór: láithreán gréasáin, nuachtlitir fhoilsithe.",
        "en": "Information its owner has already published for anyone to read: a website, a published newsletter."
      }
    }
  ],
  "RULES": [
    {
      "id": "gdpr",
      "head": {
        "ga": "Sonraí pearsanta",
        "en": "Personal data"
      },
      "text": {
        "ga": "Nuair a chuireann tú sonraí pearsanta isteach in uirlis AI, tá tú á bpróiseáil. Baineann rialacha na cosanta sonraí (GDPR) leis sin.",
        "en": "When you enter personal data into an AI tool, you are processing it. Data-protection rules (GDPR) apply."
      },
      "src": "GDPR Art. 4(1)–(2)"
    },
    {
      "id": "art4",
      "head": {
        "ga": "An tAcht AI · Airteagal 4",
        "en": "The AI Act · Article 4"
      },
      "text": {
        "ga": "Rialacha atá bunaithe ar riosca; ní toirmeasc ar AI é. Ní mór d’eagraíochtaí a úsáideann córais AI bearta a dhéanamh chun tacú le litearthacht AI a bhfoirne a fhorbairt.",
        "en": "Risk-based rules, not a ban on AI. Organisations that use AI systems must take measures to support the AI literacy of their staff."
      },
      "src": "Regulation (EU) 2024/1689, Art. 4, as replaced by Regulation (EU) 2026/1744"
    },
    {
      "id": "art50",
      "head": {
        "ga": "An tAcht AI · Airteagal 50 (ó 2 Lúnasa 2026)",
        "en": "The AI Act · Article 50 (from 2 August 2026)"
      },
      "text": {
        "ga": "Má fhoilsíonn tú téacs a ghin AI chun an pobal a chur ar an eolas faoi ábhair a bhaineann le leas an phobail, d’fhéadfadh go mbeadh ort é a nochtadh. Ní bhíonn sé de dhíth má rinneadh athbhreithniú daonna air agus go bhfuil freagracht eagarthóireachta ar dhuine ainmnithe as é a fhoilsiú.",
        "en": "If you publish AI-generated text to inform the public on matters of public interest, you may have to disclose it — unless it has had human review and a named person holds editorial responsibility for publishing it."
      },
      "src": "Regulation (EU) 2024/1689, Art. 50(4)"
    }
  ],
  "RULES_CAVEAT": {
    "ga": "Tá na rialacha ag athrú. Seiceáil an treoir is déanaí.",
    "en": "The rules are changing. Check the latest guidance."
  },
  "SESSION1_RECALL": [
    {
      "ga": "Ní hionann tuar agus tuiscint.",
      "en": "Prediction is not understanding."
    },
    {
      "ga": "Ní hionann líofa agus fíorasach.",
      "en": "Fluent is not the same as factual."
    },
    {
      "ga": "Tá tú freagrach as an méid a úsáideann tú agus a fhoilsíonn tú.",
      "en": "You remain responsible for what you use and publish."
    },
    {
      "ga": "AI don Ghaeilge — ní AI in ionad na Gaeilge.",
      "en": "AI for Irish — not AI instead of Irish."
    }
  ],
  "STOP": [
    {
      "letter": "S",
      "word": {
        "ga": "Foinse",
        "en": "Source"
      },
      "question": {
        "ga": "Cad í foinse na faisnéise seo?",
        "en": "Where did this information come from?"
      },
      "examples": [
        {
          "ga": "Ríomhphost a fuair tú ó chustaiméir",
          "en": "An email you received from a customer"
        },
        {
          "ga": "Leathanach gréasáin nach bhfuil a údar ar eolas agat",
          "en": "A web page whose author you do not know"
        }
      ]
    },
    {
      "letter": "T",
      "word": {
        "ga": "Muinín",
        "en": "Trust"
      },
      "question": {
        "ga": "An mbeadh muinín agam as an bhfaisnéis seo dá roinnfí nó dá stórálfaí í?",
        "en": "Would I trust this information if it were shared or stored?"
      },
      "help": {
        "ga": "Cá bhféadfadh sé dul ina dhiaidh sin, agus an mbeinn sásta leis?",
        "en": "Where could it end up afterwards — and would I be comfortable with that?"
      },
      "examples": [
        {
          "ga": "Uirlis phoiblí a stórálann do théacs",
          "en": "A public tool that stores your text"
        },
        {
          "ga": "Faisnéis a d’fhéadfadh dul thar do lámh",
          "en": "Information that could travel beyond your control"
        }
      ]
    },
    {
      "letter": "O",
      "word": {
        "ga": "Úinéireacht",
        "en": "Ownership"
      },
      "question": {
        "ga": "An bhfuil cead agam an fhaisnéis seo a úsáid anseo?",
        "en": "Do I have permission to use this information here?"
      },
      "examples": [
        {
          "ga": "Cáipéis atá marcáilte ‘Rúnda’",
          "en": "A document marked “Confidential”"
        },
        {
          "ga": "Téacs ó dhuine eile a chóipeáil tú",
          "en": "Text by someone else that you copied"
        }
      ]
    },
    {
      "letter": "P",
      "word": {
        "ga": "Príobháideacht",
        "en": "Privacy"
      },
      "question": {
        "ga": "An bhfuil faisnéis phearsanta, rúnda nó íogair ann?",
        "en": "Does it contain personal, confidential or sensitive information?"
      },
      "examples": [
        {
          "ga": "Ainm, seoladh, uimhir ghutháin, grianghraf",
          "en": "A name, address, phone number, photograph"
        },
        {
          "ga": "Praghsanna neamhfhoilsithe, miontuairiscí cruinnithe",
          "en": "Unpublished prices, meeting minutes"
        }
      ]
    }
  ],
  "STOP_DRILL": [
    {
      "id": "d1",
      "text": {
        "ga": "Ríomhphost ó chustaiméir le hainm, seoladh agus casaoid: “Déan níos béasaí é.”",
        "en": "A customer’s email with their name, address and complaint: “Make it politer.”"
      },
      "verdict": {
        "S": "ok",
        "T": "flag",
        "O": "flag",
        "P": "flag"
      },
      "final": "fix",
      "action": {
        "ga": "Bain an t-ainm agus an seoladh amach ar dtús.",
        "en": "Remove the name and address first."
      }
    },
    {
      "id": "d2",
      "text": {
        "ga": "Téacs do nuachtlitir fhoilsithe féin: “Aistrigh go Béarla é.”",
        "en": "Text from your own published newsletter: “Translate it into English.”"
      },
      "verdict": {
        "S": "ok",
        "T": "ok",
        "O": "ok",
        "P": "ok"
      },
      "final": "go",
      "action": {
        "ga": "Seiceáil an t-aistriúchán fós.",
        "en": "Still check the translation."
      }
    },
    {
      "id": "d3",
      "text": {
        "ga": "Treoirlínte poiblí maoinithe ón láithreán oifigiúil: “Déan achoimre orthu.”",
        "en": "A funder’s public guidelines from its official website: “Summarise them.”"
      },
      "verdict": {
        "S": "ok",
        "T": "ok",
        "O": "ok",
        "P": "ok"
      },
      "final": "go",
      "action": {
        "ga": "Seiceáil an achoimre in aghaidh na foinse.",
        "en": "Check the summary against the source."
      }
    },
    {
      "id": "d4",
      "text": {
        "ga": "Dréacht de pháipéar boird atá marcáilte ‘Rúnda’.",
        "en": "A draft board paper marked “Confidential”."
      },
      "verdict": {
        "S": "ok",
        "T": "flag",
        "O": "flag",
        "P": "flag"
      },
      "final": "stop",
      "action": {
        "ga": "Ná cuir isteach in uirlis phoiblí AI é.",
        "en": "Do not put it into a public AI tool."
      }
    },
    {
      "id": "d5",
      "text": {
        "ga": "Mír a chóipeáil tú ó shuíomh gréasáin anaithnid: “Athscríobh mar mo théacs féin í.”",
        "en": "A paragraph copied from an unknown website: “Rewrite it as my own.”"
      },
      "verdict": {
        "S": "flag",
        "T": "ok",
        "O": "flag",
        "P": "ok"
      },
      "final": "stop",
      "action": {
        "ga": "Faigh amach cé a scríobh í agus an bhfuil cead agat í a úsáid.",
        "en": "Find out who wrote it and whether you may use it."
      }
    },
    {
      "id": "d6",
      "text": {
        "ga": "Freagraí suirbhé ina bhfuil ainmneacha na rannpháirtithe: “Cad iad na príomhthéamaí?”",
        "en": "Survey responses that include participants’ names: “What are the main themes?”"
      },
      "verdict": {
        "S": "ok",
        "T": "flag",
        "O": "ok",
        "P": "flag"
      },
      "final": "fix",
      "action": {
        "ga": "Bain na hainmneacha amach ar dtús, mar a dúradh i Seisiún 1.",
        "en": "Strip the names first, as in Session 1."
      }
    }
  ],
  "TIMETABLE": [
    {
      "id": "t1",
      "time": "10:00–10:15",
      "minutes": 15,
      "kind": "reflect",
      "title": {
        "ga": "Fáilte ar ais: cad a tharla nuair a bhain tú triail as AI?",
        "en": "Welcome back: what happened when you tried AI?"
      },
      "detail": {
        "ga": "Do thrí thriail féin. Na teipeanna ar dtús.",
        "en": "Your own three experiments. Failures first."
      }
    },
    {
      "id": "t2",
      "time": "10:15–10:35",
      "minutes": 20,
      "kind": "teach",
      "title": {
        "ga": "Cad a chuaigh amú?",
        "en": "What went wrong?"
      },
      "detail": {
        "ga": "Do theipeanna féin, ar an mballa: naoi gcineál.",
        "en": "Your own failures, on the wall: nine kinds."
      }
    },
    {
      "id": "t3",
      "time": "10:35–10:55",
      "minutes": 20,
      "kind": "teach",
      "title": {
        "ga": "Sábháilteacht AI: an tástáil STOP",
        "en": "AI safety: the STOP test"
      },
      "detail": {
        "ga": "Ceithre cheist sula gcuireann tú rud ar bith isteach.",
        "en": "Four questions before you put anything in."
      }
    },
    {
      "id": "t4",
      "time": "10:55–11:20",
      "minutes": 25,
      "kind": "teach",
      "title": {
        "ga": "Príobháideacht, rúndacht agus sonraí pearsanta",
        "en": "Privacy, confidentiality and personal data"
      },
      "detail": {
        "ga": "Trí chineál faisnéise, na rialacha i gcúig nóiméad, agus cártaí a rangú.",
        "en": "Three kinds of information, the rules in five minutes, and a card sort."
      }
    },
    {
      "id": "t5",
      "time": "11:20–11:30",
      "minutes": 10,
      "kind": "break",
      "title": {
        "ga": "Sos",
        "en": "Break"
      },
      "detail": null
    },
    {
      "id": "t6",
      "time": "11:30–12:50",
      "minutes": 80,
      "kind": "lab",
      "title": {
        "ga": "Príomhcheardlann: Ó AI go hObair",
        "en": "Main workshop: from AI to work"
      },
      "detail": {
        "ga": "Trí dhúshlán: AI → AI · Togra → Athbhreithniú · Togra → Cur chun cinn",
        "en": "Three challenges: AI → AI · Proposal → Review · Proposal → Promotion"
      }
    },
    {
      "id": "t7",
      "time": "12:50–12:55",
      "minutes": 5,
      "kind": "lab",
      "title": {
        "ga": "Do shruth oibre sábháilte AI féin",
        "en": "Build your own safe AI workflow"
      },
      "detail": {
        "ga": "Tasc → Foinse → Prompt → Gin → Fíoraigh → Feabhsaigh → Ceadú",
        "en": "Task → Source → Prompt → Generate → Verify → Improve → Approve"
      }
    },
    {
      "id": "t8",
      "time": "12:55–13:00",
      "minutes": 5,
      "kind": "reflect",
      "title": {
        "ga": "Machnamh agus ar aghaidh go Seisiún 3",
        "en": "Reflection, and on to Session 3"
      },
      "detail": {
        "ga": "AI don Ghaeilge — ní AI in ionad na Gaeilge.",
        "en": "AI for Irish — not AI instead of Irish."
      }
    }
  ],
  "TWO_STOPS": {
    "out": {
      "tag": {
        "ga": "Amach · Seisiún 1",
        "en": "Out · Session 1"
      },
      "line": {
        "ga": "Cad a dhéanaim leis an aschur?",
        "en": "What do I do with what comes OUT?"
      },
      "words": "Stop · Think · Observe · Proceed"
    },
    "in": {
      "tag": {
        "ga": "Isteach · Seisiún 2",
        "en": "In · Session 2"
      },
      "line": {
        "ga": "Cad a chuirim isteach?",
        "en": "What do I put IN?"
      },
      "words": "Source · Trust · Ownership · Privacy"
    },
    "note": {
      "ga": "Dhá STOP, dhá threo. An ceann seo: sula gcuireann tú rud isteach.",
      "en": "Two STOPs, two directions. This one is for before you put anything in."
    }
  },
  "WELCOME": {
    "intro": {
      "ga": "Bhain tú triail as AI trí huaire idir Seisiún 1 agus inniu. Na teipeanna ar dtús.",
      "en": "You tried AI three times between Session 1 and today. Failures first."
    },
    "questions": [
      {
        "ga": "Cad a bhain tú triail as?",
        "en": "What did you try?"
      },
      {
        "ga": "Cad a d’oibrigh go maith?",
        "en": "What worked?"
      },
      {
        "ga": "Cad nár oibrigh?",
        "en": "What failed?"
      },
      {
        "ga": "Cad a chuir ionadh ort?",
        "en": "What surprised you?"
      },
      {
        "ga": "Ar shábháil AI am duit?",
        "en": "Did AI save time?"
      },
      {
        "ga": "An raibh ort an t-aschur a cheartú?",
        "en": "Did you have to correct it?"
      },
      {
        "ga": "Ar chruthaigh AI fadhb?",
        "en": "Did AI create a problem?"
      },
      {
        "ga": "An raibh muinín agat as rud a bhí mícheart i ndáiríre?",
        "en": "Did you trust something that turned out to be wrong?"
      }
    ],
    "recordColumns": [
      {
        "ga": "Tasc",
        "en": "Task"
      },
      {
        "ga": "Prompt",
        "en": "Prompt"
      },
      {
        "ga": "Aschur",
        "en": "Output"
      },
      {
        "ga": "Cad a d’oibrigh",
        "en": "What worked"
      },
      {
        "ga": "Cad nár oibrigh",
        "en": "What did not"
      },
      {
        "ga": "Cad a d’fhoghlaim mé",
        "en": "What I learned"
      }
    ],
    "flow": [
      {
        "min": 5,
        "what": {
          "ga": "I mbeirteanna: inis do chomhpháirtí faoi thriail amháin.",
          "en": "In pairs: tell your partner about one experiment."
        }
      },
      {
        "min": 8,
        "what": {
          "ga": "Sa seomra: trí nó ceithre scéal. Ar an mballa: d’oibrigh / theip / chuir ionadh orm.",
          "en": "In the room: three or four stories. On the wall: worked / failed / surprised."
        }
      },
      {
        "min": 2,
        "what": {
          "ga": "Balla na n-ábhar imní ó Sheisiún 1: cé acu a chuaigh i bhfeidhm ort?",
          "en": "The Session 1 concerns wall: which did your experience touch?"
        }
      }
    ],
    "handsUp": {
      "ga": "Ardaigh do lámh: ar shábháil sé am? ar cheartaigh tú é? ar chruthaigh sé fadhb?",
      "en": "Hands up: did it save time? did you correct it? did it create a problem?"
    }
  },
  "BETWEEN": {
    "title": {
      "ga": "Ó thasc go sruth oibre",
      "en": "From task to workflow"
    },
    "brief": {
      "ga": "Roghnaigh tasc cumarsáide a dhéanann tú go rialta — nuachtlitir, fógra imeachta, post sóisialta, cuireadh ríomhphoist, nó aon rud eile — agus déan sruth oibre de. Tabhair leat an sruth oibre, agus an pointe ar theip air, go Seisiún 3.",
      "en": "Choose one repetitive communication task — a newsletter, an event announcement, a social post, an email invitation, or anything else — and turn it into a workflow. Bring the workflow, and the point where it broke, to Session 3."
    }
  },
  "C1": {
    "id": "c1",
    "min": 10,
    "time": "11:30–11:40",
    "title": {
      "ga": "Dúshlán 1: AI → AI",
      "en": "Challenge 1: AI → AI"
    },
    "goal": {
      "ga": "Iarr ar AI amháin prompt a dhearadh do AI eile.",
      "en": "Ask one AI to design a prompt for another AI."
    },
    "flow": {
      "ga": "AI a chruthaíonn prompt → duine a sheiceálann an prompt → an dara AI a dhéanann an tasc → duine a sheiceálann an t-aschur",
      "en": "AI creates prompt → human checks prompt → second AI performs task → human checks result"
    },
    "metaPrompt": {
      "ga": "Teastaíonn uaim go ndéanfadh córas AI eile athbhreithniú ar thogra maoinithe atá scríofa i nGaeilge. Dear prompt mionsonraithe a chuirfidh an dara AI ag gníomhú mar athbhreithneoir criticiúil togra. Ba cheart dó struchtúr, soiléireacht, comhsheasmhacht, fianaise, cáilíocht teanga agus éilimh gan tacaíocht a sheiceáil. Ní mór dó gan faisnéis a chumadh agus gan an togra a athscríobh mura n-iarrtar go sainráite air é.",
      "en": "I need another AI system to review a funding proposal written in Irish. Design a detailed prompt that will make the second AI act as a critical proposal reviewer. It should check structure, clarity, consistency, evidence, language quality and unsupported claims. It must not invent information or rewrite the proposal unless explicitly asked."
    },
    "promptChecklist": [
      {
        "ga": "An luaitear ról an athbhreithneora chriticiúil?",
        "en": "Does it name the role of a critical reviewer?"
      },
      {
        "ga": "An liostaítear cad atá le seiceáil?",
        "en": "Does it list what to check?"
      },
      {
        "ga": "An bhfuil sé ráite go soiléir gan faisnéis a chumadh?",
        "en": "Does it clearly say not to invent information?"
      },
      {
        "ga": "An iarrtar air idirdhealú a dhéanamh idir earráid chinnte, feabhsú féideartha agus rud a chaithfidh duine a fhíorú?",
        "en": "Does it ask it to separate a definite error, a possible improvement and something a human must verify?"
      },
      {
        "ga": "An bhfuil sé ráite gan an togra a athscríobh go fóill?",
        "en": "Does it say not to rewrite the proposal yet?"
      },
      {
        "ga": "An iarrtar air cáilíocht na Gaeilge a sheiceáil, agus na téarmaí nach bhfuil sé cinnte fúthu a liostú?",
        "en": "Does it ask for Irish-language quality checks, and a list of terms it was unsure about?"
      }
    ],
    "message": {
      "ga": "Ní ráthaíonn prompt níos fearr freagra ceart.",
      "en": "A better prompt does not guarantee a correct answer."
    },
    "twoAI": {
      "ga": "Dhá uirlis éagsúla, nó comhrá nua. Mura bhfuil ach uirlis amháin agat, tá seans go mbeidh na laigí céanna aici.",
      "en": "Two different tools, or a fresh chat. With only one tool, it may share the same blind spots."
    }
  },
  "C2": {
    "id": "c2",
    "min": 18,
    "time": "11:40–11:58",
    "title": {
      "ga": "Dúshlán 2: Togra → Athbhreithniú",
      "en": "Challenge 2: Proposal → Review"
    },
    "rule": {
      "ga": "Athbhreithniú ar dtús → athscríobh ina dhiaidh.",
      "en": "Review first → rewrite second."
    },
    "reviewPrompt": {
      "ga": "Gníomhaigh mar athbhreithneoir criticiúil togra. Déan athbhreithniú ar an togra seo sula gcuirtear isteach é. Seiceáil: soiléireacht; struchtúr; cuspóirí; comhsheasmhacht; fianaise; éilimh gan tacaíocht; faisnéis atá ar iarraidh; cáilíocht na Gaeilge; téarmaíocht; inléiteacht; oiriúnacht don lucht féachana atá beartaithe. Ná cum fíricí. Déan idirdhealú soiléir idir: 1. earráid chinnte, 2. feabhsú féideartha, 3. rud a chaithfidh duine a fhíorú. Ná hathscríobh an togra go fóill.",
      "en": "Act as a critical proposal reviewer. Review this proposal before submission. Check: clarity; structure; objectives; consistency; evidence; unsupported claims; missing information; Irish-language quality; terminology; readability; suitability for the intended audience. Do not invent facts. Clearly distinguish: 1. a definite error, 2. a possible improvement, 3. something requiring human verification. Do not rewrite the proposal yet."
    },
    "categories": [
      {
        "id": "definite",
        "label": {
          "ga": "Earráid chinnte",
          "en": "Definite error"
        }
      },
      {
        "id": "improve",
        "label": {
          "ga": "Feabhsú féideartha",
          "en": "Possible improvement"
        }
      },
      {
        "id": "verify",
        "label": {
          "ga": "Rud a chaithfidh duine a fhíorú",
          "en": "Requires human verification"
        }
      }
    ],
    "decisions": [
      {
        "id": "accept",
        "label": {
          "ga": "Glac leis",
          "en": "Accept"
        }
      },
      {
        "id": "edit",
        "label": {
          "ga": "Ceartaigh",
          "en": "Edit"
        }
      },
      {
        "id": "reject",
        "label": {
          "ga": "Diúltaigh",
          "en": "Reject"
        }
      }
    ],
    "reviseRule": {
      "ga": "Roghnaigh trí rud. Is féidir leat moladh a iarraidh ar AI faoi na trí rud sin amháin. Ansin déanann tusa an cinneadh.",
      "en": "Choose three items. You may ask AI to SUGGEST a fix for those three only. Then you decide."
    },
    "diffRule": {
      "ga": "Déan comparáid idir an dá leagan: ní hamháin an prós, ach an t-éileamh.",
      "en": "Diff the claim, not just the prose."
    },
    "output": {
      "ga": "Achoimre fhíoraithe (8 líne ar a mhéad). Cuir [le fíorú] ar aon rud nach bhfuil deimhnithe.",
      "en": "A verified summary (8 lines at most). Mark anything unconfirmed [to verify]."
    },
    "organiserAt": {
      "ga": "Ag 11:52 tugtar Freagra an Eagraí do gach grúpa.",
      "en": "At 11:52 each group receives the Organiser’s Reply."
    }
  },
  "C3": {
    "id": "c3",
    "min": 52,
    "time": "11:58–12:50",
    "title": {
      "ga": "Dúshlán 3: Togra → Cur chun cinn",
      "en": "Challenge 3: Proposal → Promotion"
    },
    "subtitle": {
      "ga": "Cumarsáid le cabhair ó AI",
      "en": "AI-assisted communication"
    },
    "flow": {
      "ga": "Faisnéis fhíoraithe → dréacht AI → seiceáil dhaonna → dearadh → ceadú daonna deiridh",
      "en": "VERIFIED INFORMATION → AI DRAFT → HUMAN CHECK → DESIGN → FINAL HUMAN APPROVAL"
    },
    "outputs": [
      {
        "id": "o1",
        "label": {
          "ga": "Fógra poiblí i nGaeilge",
          "en": "A public announcement in Irish"
        },
        "parts": {
          "ga": "ceannlíne · cur síos in aon abairt · trí thairbhe · treoir chun gnímh",
          "en": "headline · one-sentence description · three benefits · call to action"
        }
      },
      {
        "id": "o2",
        "label": {
          "ga": "Leagan Béarla",
          "en": "An English version"
        },
        "parts": {
          "ga": "scríofa mar Bhéarla, ní focal ar fhocal",
          "en": "written as English, not word for word"
        }
      },
      {
        "id": "o3",
        "label": {
          "ga": "Post gearr do na meáin shóisialta",
          "en": "A short social media post"
        },
        "parts": {
          "ga": "Gaeilge, méid fóin",
          "en": "in Irish, phone-sized"
        }
      },
      {
        "id": "o4",
        "label": {
          "ga": "Cuireadh ríomhphoist",
          "en": "An email invitation"
        },
        "parts": {
          "ga": "líne an ábhair i mBéarla agus i nGaeilge · corp i nGaeilge",
          "en": "subject line in Irish and English · body in Irish"
        }
      }
    ],
    "promptTemplate": {
      "ga": "Ag úsáid na faisnéise fíoraithe thíos AMHÁIN, scríobh: (1) fógra poiblí i nGaeilge (ceannlíne, cur síos in aon abairt, trí thairbhe, treoir chun gnímh); (2) leagan Béarla nádúrtha — scríofa mar Bhéarla, ní focal ar fhocal; (3) post gearr Gaeilge do na meáin shóisialta; (4) cuireadh ríomhphoist i nGaeilge. Má tá sonra ar iarraidh (dáta, am, ionad, praghas, nasc clárúcháin, sonraí teagmhála), fág bearna atá marcáilte go soiléir idir lúibíní cearnacha seachas ceann a chumadh. Ná cum dátaí, ionaid, praghsanna, maoiniú, naisc, sonraí teagmhála, incháilitheacht, staitisticí, teistiméireachtaí ná éilimh oifigiúla. Ag an deireadh, liostaigh aon téarmaí Gaeilge nach raibh tú cinnte fúthu. FAISNÉIS FHÍORAITHE: [greamaigh anseo]",
      "en": "Using ONLY the verified information below, write: (1) an Irish-language public announcement (headline, one-sentence description, three benefits, call to action); (2) a natural English version — written as English, not word for word; (3) a short Irish social media post; (4) an email invitation in Irish. If a detail is missing (date, time, venue, price, registration link, contact details), leave a clearly marked gap in square brackets rather than inventing it. Do not invent dates, locations, prices, funding, links, contact information, eligibility, statistics, testimonials or official organisational claims. At the end, list any Irish terms you were unsure about. VERIFIED INFORMATION: [paste here]"
    },
    "noInvent": [
      {
        "ga": "Dátaí",
        "en": "Dates"
      },
      {
        "ga": "Ionaid",
        "en": "Locations"
      },
      {
        "ga": "Praghsanna",
        "en": "Prices"
      },
      {
        "ga": "Maoiniú",
        "en": "Funding"
      },
      {
        "ga": "Naisc chlárúcháin",
        "en": "Registration links"
      },
      {
        "ga": "Sonraí teagmhála",
        "en": "Contact information"
      },
      {
        "ga": "Incháilitheacht",
        "en": "Eligibility"
      },
      {
        "ga": "Staitisticí",
        "en": "Statistics"
      },
      {
        "ga": "Teistiméireachtaí",
        "en": "Testimonials"
      },
      {
        "ga": "Éilimh oifigiúla thar ceann eagraíochta",
        "en": "Official organisational claims"
      }
    ],
    "noInventLine": {
      "ga": "Níor cheart do AI aon cheann díobh seo a chumadh mura bhfuil siad san fhaisnéis fhíoraithe.",
      "en": "AI must not invent any of these unless they are in the verified information."
    },
    "sameMeaning": {
      "ga": "Cuir na leaganacha i gcomparáid le chéile. An ndearna AI athrú ar an mbrí? Déan comparáid idir an t-éileamh, ní hamháin idir an prós.",
      "en": "Compare the versions. Did the AI change the meaning? Diff the claim, not just the prose."
    },
    "canva": {
      "message": {
        "ga": "Cuidíonn Canva leis an gcur i láthair. Ní dhéanann sé fíricí a fhíorú.",
        "en": "Canva helps with presentation. It does not verify facts."
      },
      "steps": [
        {
          "ga": "Úsáid an téacs ceadaithe amháin. Ná scríobh téacs nua sa dearadh.",
          "en": "Use the approved text only. Do not write new text in the design."
        },
        {
          "ga": "Roghnaigh teimpléad: póstaer A4, nó cearnóg 1080 × 1080 do na meáin shóisialta.",
          "en": "Choose a template: an A4 poster, or a 1080 × 1080 square for social media."
        },
        {
          "ga": "Fág na bearnaí marcáilte le feiceáil: [dáta], [ionad], [praghas].",
          "en": "Keep the marked gaps visible: [date], [venue], [price]."
        },
        {
          "ga": "Seiceáil go bhfuil na síntí fada ceart sa chló.",
          "en": "Check that the fadas display correctly in the font."
        },
        {
          "ga": "Ná húsáid lógó fíor nó branda bréagach. Ná húsáid daoine cruthaithe ag AI.",
          "en": "No real logos, no fake branding, no AI-generated people."
        },
        {
          "ga": "Seiceáil codarsnacht agus téacs malartach (alt text) don íomhá.",
          "en": "Check contrast, and add alt text."
        }
      ],
      "fallback": {
        "ga": "Gan Canva? Bain úsáid as PowerPoint, Word nó pár agus peann.",
        "en": "No Canva? Use PowerPoint, Word, or paper and pen."
      }
    },
    "approval": {
      "signed": {
        "ga": "Ceadaithe ag: ____________  Dáta: ____________",
        "en": "Approved by: ____________  Date: ____________"
      },
      "notYet": {
        "ga": "Gan cheadú go fóill. Cad atá ar iarraidh?",
        "en": "Not approved yet. What is missing?"
      }
    },
    "transparency": {
      "ga": "Má fhoilsíonn tú é seo i ndáiríre, seiceáil rialacha trédhearcachta Airteagal 50.",
      "en": "If you were to really publish this, check the Article 50 transparency rules."
    },
    "extensions": [
      {
        "ga": "Mír nuachtlitreach i nGaeilge, agus leagan atá oiriúnach don fhón.",
        "en": "A newsletter item in Irish, and a phone-friendly version."
      },
      {
        "ga": "Comhroinn teachtaireacht amháin idir dhá ardán éagsúla.",
        "en": "Adapt one message for two different platforms."
      },
      {
        "ga": "Aistrigh ón mBéarla go Gaeilge, agus ansin seiceáil an bhrí ar ais.",
        "en": "Translate from English into Irish, then check the meaning back."
      }
    ]
  },
  "CHAIN": [
    {
      "id": "c_proposal",
      "actor": "doc",
      "label": {
        "ga": "Togra",
        "en": "Proposal"
      }
    },
    {
      "id": "c_ai_review",
      "actor": "ai",
      "label": {
        "ga": "Athbhreithniú AI",
        "en": "AI review"
      }
    },
    {
      "id": "c_human_revision",
      "actor": "human",
      "label": {
        "ga": "Eagarthóireacht dhaonna",
        "en": "Human revision"
      }
    },
    {
      "id": "c_ai_promo",
      "actor": "ai",
      "label": {
        "ga": "Cur chun cinn le AI",
        "en": "AI promotion"
      }
    },
    {
      "id": "c_human_approval",
      "actor": "human",
      "label": {
        "ga": "Ceadú daonna",
        "en": "Human approval"
      }
    }
  ],
  "DEFECTS": [
    {
      "id": "D1",
      "what": {
        "ga": "Cuspóir doiléir",
        "en": "Vague objective"
      },
      "cat": "improve",
      "where": "Objective",
      "why": "“Do things better” says nothing measurable. What will participants be able to do afterwards?",
      "fix": "State one measurable outcome (e.g. write and check a short announcement in Irish)."
    },
    {
      "id": "D2",
      "what": {
        "ga": "Éileamh gan tacaíocht",
        "en": "Unsupported claim"
      },
      "cat": "verify",
      "where": "Background",
      "why": "“90%” has no source, no sample, no date. Precise-sounding numbers are exactly where fabrication hides (Session 1).",
      "fix": "Find the source, or remove the figure."
    },
    {
      "id": "D3",
      "what": {
        "ga": "Uimhir neamhréireach",
        "en": "Inconsistent number"
      },
      "cat": "definite",
      "where": "Programme vs Participants",
      "why": "24 places in one section, a maximum of 20 in another.",
      "fix": "Ask the organiser which is right."
    },
    {
      "id": "D4",
      "what": {
        "ga": "Fianaise lag",
        "en": "Weak evidence"
      },
      "cat": "improve",
      "where": "Evidence",
      "why": "“Some people said…” — who, how many, what exactly?",
      "fix": "Give counts and a source, or drop it."
    },
    {
      "id": "D5",
      "what": {
        "ga": "Sprioclucht neamhchinnte",
        "en": "Unclear target audience"
      },
      "cat": "improve",
      "where": "Objective",
      "why": "“People in the community” is everyone and no-one.",
      "fix": "Name the audience (the organiser’s reply does)."
    },
    {
      "id": "D6",
      "what": {
        "ga": "Athrá",
        "en": "Repetition"
      },
      "cat": "improve",
      "where": "Programme",
      "why": "The same sentence twice, the second only louder.",
      "fix": "Say it once, with an example."
    },
    {
      "id": "D7",
      "what": {
        "ga": "Abairt ait Ghaeilge",
        "en": "Awkward Irish sentence"
      },
      "cat": "definite",
      "where": "Programme",
      "why": "“ag dul a bheith ábalta” is English “going to be able to” in Irish clothes; “níos éifeachtaí” is not the natural way to say “more effectively”.",
      "fix": "Beidh na rannpháirtithe in ann an teicneolaíocht a úsáid ar bhealach níos éifeachtaí. (Grammar checkers do not catch this — a person does.)"
    },
    {
      "id": "D8",
      "what": {
        "ga": "Frása Béarla gan ghá",
        "en": "Unnecessary English phrase"
      },
      "cat": "improve",
      "where": "Programme",
      "why": "“value for money” has an established Irish term.",
      "fix": "luach ar airgead (Téarma, Business » Commerce)."
    },
    {
      "id": "D9",
      "what": {
        "ga": "Éileamh a chaithfidh duine a fhíorú",
        "en": "Claim requiring human verification"
      },
      "cat": "verify",
      "where": "Evidence",
      "why": "“The only programme of its kind in Ireland” is a checkable, very risky claim.",
      "fix": "Verify it, or remove it."
    }
  ],
  "IRISH_CHECKS": [
    {
      "id": "i1",
      "label": {
        "ga": "Gramadach",
        "en": "Grammar"
      },
      "ask": {
        "ga": "Séimhiú, urú, tuiseal, foirmeacha na mbriathra.",
        "en": "Lenition, eclipsis, case, verb forms."
      }
    },
    {
      "id": "i2",
      "label": {
        "ga": "Litriú",
        "en": "Spelling"
      },
      "ask": {
        "ga": "Na síntí fada agus litriú caighdeánach.",
        "en": "Fadas and standard spelling."
      }
    },
    {
      "id": "i3",
      "label": {
        "ga": "Comhréir",
        "en": "Syntax"
      },
      "ask": {
        "ga": "Ord na bhfocal: an bhfuil sé mar a bheadh sa Ghaeilge?",
        "en": "Word order: is it how Irish would put it?"
      }
    },
    {
      "id": "i4",
      "label": {
        "ga": "Nádúrthacht",
        "en": "Naturalness"
      },
      "ask": {
        "ga": "An ndéarfadh duine é seo?",
        "en": "Would a person actually say this?"
      }
    },
    {
      "id": "i5",
      "label": {
        "ga": "Nathanna cainte",
        "en": "Idiomatic usage"
      },
      "ask": {
        "ga": "An bhfuil nathanna cainte na Gaeilge ann, nó focail aistrithe amháin?",
        "en": "Real Irish idiom, or only translated words?"
      }
    },
    {
      "id": "i6",
      "label": {
        "ga": "Téarmaíocht",
        "en": "Terminology"
      },
      "ask": {
        "ga": "Seiceáil téarma.ie agus focloir.ie.",
        "en": "Check téarma.ie and focloir.ie."
      }
    },
    {
      "id": "i7",
      "label": {
        "ga": "Réim theanga",
        "en": "Register"
      },
      "ask": {
        "ga": "An oireann sé don léitheoir agus don ócáid?",
        "en": "Does it suit the reader and the occasion?"
      }
    },
    {
      "id": "i8",
      "label": {
        "ga": "Comhsheasmhacht",
        "en": "Consistency"
      },
      "ask": {
        "ga": "An úsáidtear an focal céanna don rud céanna i gcónaí?",
        "en": "Is the same word always used for the same thing?"
      }
    },
    {
      "id": "i9",
      "label": {
        "ga": "Béarla aistrithe focal ar fhocal",
        "en": "Calques from English"
      },
      "ask": {
        "ga": "Aimsigh frásaí atá cruthaithe ón mBéarla.",
        "en": "Find phrases built from English."
      }
    },
    {
      "id": "i10",
      "label": {
        "ga": "Oiriúnacht chultúrtha",
        "en": "Cultural appropriateness"
      },
      "ask": {
        "ga": "An oireann sé don phobal agus don ócáid?",
        "en": "Does it suit the community and the occasion?"
      }
    },
    {
      "id": "i11",
      "label": {
        "ga": "Brí i gcomparáid leis an mbunleagan Béarla",
        "en": "Meaning against the English source"
      },
      "ask": {
        "ga": "An gcomhfhreagraíonn an Ghaeilge don bhunleagan?",
        "en": "Does the Irish match the English source?"
      }
    }
  ],
  "IRISH_MESSAGE": {
    "ga": "Ní mór do dhuine a bhfuil Gaeilge mhaith aige nó aici an Ghaeilge a ghin AI a sheiceáil i gcónaí.",
    "en": "AI-generated Irish must always be checked by a person with good Irish."
  },
  "IRISH_TOOL_NOTE": {
    "ga": "Is seiceáil bhreise úsáideach é An Gramadóir (cadhan.com), ach ní hé an focal deiridh é.",
    "en": "An Gramadóir (cadhan.com) is a useful extra check, but never the final word."
  },
  "NINE_CHECKS": [
    {
      "id": "n1",
      "label": {
        "ga": "Cruinneas fíorasach",
        "en": "Factual accuracy"
      },
      "ask": {
        "ga": "An bhfuil gach fíric cheart agus fíoraithe?",
        "en": "Is every fact right, and verified?"
      }
    },
    {
      "id": "n2",
      "label": {
        "ga": "Gramadach",
        "en": "Grammar"
      },
      "ask": {
        "ga": "An bhfuil an ghramadach cheart?",
        "en": "Is the grammar right?"
      }
    },
    {
      "id": "n3",
      "label": {
        "ga": "Téarmaíocht Ghaeilge",
        "en": "Irish terminology"
      },
      "ask": {
        "ga": "An iad seo na téarmaí cearta? (téarma.ie)",
        "en": "Are these the right terms? (téarma.ie)"
      }
    },
    {
      "id": "n4",
      "label": {
        "ga": "Ton",
        "en": "Tone"
      },
      "ask": {
        "ga": "An bhfuil an ton ceart don ócáid?",
        "en": "Is the tone right for the occasion?"
      }
    },
    {
      "id": "n5",
      "label": {
        "ga": "Oiriúnacht don lucht féachana",
        "en": "Audience suitability"
      },
      "ask": {
        "ga": "An dtuigfidh an léitheoir é ar an gcéad léamh?",
        "en": "Will the reader understand it on first reading?"
      }
    },
    {
      "id": "n6",
      "label": {
        "ga": "Oiriúnacht chultúrtha",
        "en": "Cultural appropriateness"
      },
      "ask": {
        "ga": "An oireann sé don phobal seo?",
        "en": "Does it suit this community?"
      }
    },
    {
      "id": "n7",
      "label": {
        "ga": "Faisnéis chumtha",
        "en": "Invented information"
      },
      "ask": {
        "ga": "An bhfuil sonra ann nár tugadh don AI?",
        "en": "Is there a detail the AI was never given?"
      }
    },
    {
      "id": "n8",
      "label": {
        "ga": "Éilimh gan tacaíocht",
        "en": "Unsupported claims"
      },
      "ask": {
        "ga": "An bhfuil éileamh ann nach bhfuil fianaise leis?",
        "en": "Is there a claim with no evidence?"
      }
    },
    {
      "id": "n9",
      "label": {
        "ga": "An bhrí",
        "en": "The meaning"
      },
      "ask": {
        "ga": "An ndearna AI athrú ar an mbrí bhunaidh?",
        "en": "Did the AI change the original meaning?"
      }
    }
  ],
  "NINE_KEY": {
    "ga": "Ní hionann líofa agus fíorasach.",
    "en": "Fluent is not automatically correct."
  },
  "ORGANISER_REPLY": {
    "head": {
      "ga": "Freagra an Eagraí (ficseanúil)",
      "en": "The Organiser’s Reply (fictional)"
    },
    "ga": "Go raibh maith agaibh as bhur gceisteanna. Tá 20 áit ann. Is é an sprioclucht ná úinéirí agus foireann gnóthaí beaga agus grúpaí pobail sa Ghaeltacht. Beidh na seisiúin i nGaeilge: dhá uair an chloig, tráthnóna amháin sa tseachtain, ar feadh sé seachtaine. Ní féidir linn an figiúr 90% a dheimhniú — bainigí amach é. Ní féidir linn a dheimhniú gurb é seo an t-aon chlár den chineál seo — bainigí amach é. Tá aiseolas ón mbliain seo caite ann, ach níor bhailíomar é — fágaigí amach é. Níl na dátaí, an t-ionad, an praghas ná conas clárú deimhnithe fós.",
    "en": "Thank you for your questions. We have 20 places. The audience is owners and staff of small businesses and community groups in the Gaeltacht. The sessions will be in Irish: six weeks, two hours each, one evening a week. We cannot confirm the 90% figure — please remove it. We cannot confirm that this is the only programme of its kind — please remove it. There is feedback from last year, but we did not collect it — leave it out. The dates, the venue, the price and how to register are not yet confirmed.",
    "verified": [
      {
        "ga": "Teideal: Scríobh go Soiléir, Fógair go Cliste",
        "en": "Title: Write Clearly, Promote Smartly"
      },
      {
        "ga": "Do: úinéirí agus foireann gnóthaí beaga agus grúpaí pobail sa Ghaeltacht",
        "en": "For: owners and staff of small businesses and community groups in the Gaeltacht"
      },
      {
        "ga": "Formáid: dhá uair an chloig, tráthnóna amháin sa tseachtain, ar feadh sé seachtaine",
        "en": "Format: two hours, one evening a week, for six weeks"
      },
      {
        "ga": "Teanga: Gaeilge",
        "en": "Language: Irish"
      },
      {
        "ga": "Áiteanna: 20",
        "en": "Places: 20"
      },
      {
        "ga": "Dáta, ionad, praghas, conas clárú: [le fíorú]",
        "en": "Date, venue, price, how to register: [to verify]"
      }
    ]
  },
  "PROPOSAL": {
    "label": {
      "ga": "Sampla oiliúna ficseanúil — le haghaidh oiliúna amháin",
      "en": "FICTIONAL TRAINING EXAMPLE – FOR TRAINING ONLY"
    },
    "title": {
      "ga": "Togra oiliúna: Scríobh go Soiléir, Fógair go Cliste",
      "en": "Training proposal: Write Clearly, Promote Smartly"
    },
    "org": {
      "ga": "Comharchumann Lios na Scéalta (ainm ficseanúil)",
      "en": "Lios na Scéalta Co-operative (fictional name)"
    },
    "sections": [
      {
        "id": "background",
        "head": {
          "ga": "Cúlra",
          "en": "Background"
        },
        "paras": [
          {
            "defect": "D2",
            "t": {
              "ga": "Tá gá mór le hoiliúint nua sa Ghaeltacht. Tá 90% de ghnóthaí beaga na Gaeltachta ag lorg oiliúna in AI.",
              "en": "There is a great need for new training in the Gaeltacht. 90% of small businesses in the Gaeltacht are looking for AI training."
            }
          }
        ]
      },
      {
        "id": "objective",
        "head": {
          "ga": "Cuspóir",
          "en": "Objective"
        },
        "paras": [
          {
            "defect": "D1 D5",
            "t": {
              "ga": "Is é cuspóir an chláir seo cabhrú le daoine sa phobal rudaí a dhéanamh níos fearr.",
              "en": "The aim of this programme is to help people in the community do things better."
            }
          }
        ]
      },
      {
        "id": "programme",
        "head": {
          "ga": "An clár",
          "en": "The programme"
        },
        "paras": [
          {
            "defect": "D3",
            "t": {
              "ga": "Beidh an clár ar siúl ar feadh sé seachtaine. Beidh áit ann do 24 rannpháirtí.",
              "en": "The programme will run for six weeks. There will be a place for 24 participants."
            }
          },
          {
            "defect": "D6",
            "t": {
              "ga": "Beidh an clár praiticiúil. Beidh an clár an-phraiticiúil.",
              "en": "The programme will be practical. The programme will be very practical."
            }
          },
          {
            "defect": "D7",
            "t": {
              "ga": "Beidh na rannpháirtithe ag dul a bheith ábalta an teicneolaíocht a úsáid níos éifeachtaí.",
              "en": "The participants will be going to be able to use the technology more effectively."
            }
          },
          {
            "defect": "D8",
            "t": {
              "ga": "Tabharfaidh an clár ‘value for money’ do na rannpháirtithe.",
              "en": "The programme will give the participants “value for money”."
            }
          }
        ]
      },
      {
        "id": "evidence",
        "head": {
          "ga": "Fianaise",
          "en": "Evidence"
        },
        "paras": [
          {
            "defect": "D4",
            "t": {
              "ga": "Dúirt roinnt daoine gur thaitin an clár leo anuraidh.",
              "en": "Some people said they liked the programme last year."
            }
          },
          {
            "defect": "D9",
            "t": {
              "ga": "Is é seo an t-aon chlár den chineál seo in Éirinn.",
              "en": "This is the only programme of its kind in Ireland."
            }
          }
        ]
      },
      {
        "id": "participants",
        "head": {
          "ga": "Rannpháirtithe",
          "en": "Participants"
        },
        "paras": [
          {
            "defect": "D3",
            "t": {
              "ga": "Is é 20 an líon is mó rannpháirtithe.",
              "en": "The maximum number of participants is 20."
            }
          }
        ]
      },
      {
        "id": "practical",
        "head": {
          "ga": "Sonraí praiticiúla",
          "en": "Practical details"
        },
        "paras": [
          {
            "defect": "",
            "t": {
              "ga": "Dátaí: [le deimhniú]. Ionad: [le deimhniú]. Praghas: [le deimhniú]. Conas clárú: [le deimhniú].",
              "en": "Dates: [to be confirmed]. Venue: [to be confirmed]. Price: [to be confirmed]. How to register: [to be confirmed]."
            }
          }
        ]
      }
    ]
  },
  "REFLECTION": {
    "questions": [
      {
        "ga": "Rud amháin a dhéanfaidh AI dom, agus a choinneoidh mé.",
        "en": "One thing AI will do for me, that I will keep."
      },
      {
        "ga": "Seiceáil amháin nach gcaillfidh mé choíche.",
        "en": "One check I will never skip."
      },
      {
        "ga": "Rud amháin nach ligfidh mé do AI a dhéanamh: é a cheadú.",
        "en": "One thing I will not let AI do: approve it."
      }
    ],
    "bridge": {
      "ga": "Seisiún 3: cad a tharlaíonn nuair a bhuaileann AI leis an nGaeilge?",
      "en": "Session 3: what happens when AI meets Irish?"
    }
  },
  "ROLES": [
    {
      "ga": "An duine atá freagrach as an tasc",
      "en": "Task owner"
    },
    {
      "ga": "Oibreoir AI / scríbhneoir an ‘prompt’",
      "en": "AI operator / prompt writer"
    },
    {
      "ga": "Seiceálaí / amhrasach",
      "en": "Checker / sceptic"
    },
    {
      "ga": "An duine a cheadaíonn (ainmnithe)",
      "en": "Named approver"
    }
  ],
  "STEPS": [
    {
      "n": 1,
      "ch": 1,
      "actor": "ai",
      "min": 3,
      "what": {
        "ga": "AI a chruthaíonn prompt an athbhreithneora.",
        "en": "AI creates the reviewer prompt."
      }
    },
    {
      "n": 2,
      "ch": 1,
      "actor": "human",
      "min": 7,
      "what": {
        "ga": "Duine a sheiceálann an prompt, agus a cheartaíonn é.",
        "en": "A human checks the prompt, and fixes it."
      }
    },
    {
      "n": 3,
      "ch": 2,
      "actor": "ai",
      "min": 6,
      "what": {
        "ga": "An dara AI a dhéanann athbhreithniú ar an togra.",
        "en": "A second AI reviews the proposal."
      }
    },
    {
      "n": 4,
      "ch": 2,
      "actor": "human",
      "min": 4,
      "what": {
        "ga": "Duine a sheiceálann an t-athbhreithniú.",
        "en": "A human checks the review."
      }
    },
    {
      "n": 5,
      "ch": 2,
      "actor": "human",
      "min": 8,
      "what": {
        "ga": "Eagarthóireacht dhaonna: glac leis, ceartaigh, nó diúltaigh.",
        "en": "Human revision: accept, edit, or reject."
      }
    },
    {
      "n": 6,
      "ch": 3,
      "actor": "ai",
      "min": 6,
      "what": {
        "ga": "AI a dhréachtaíonn an chumarsáid, ón bhfaisnéis fhíoraithe amháin.",
        "en": "AI drafts the communication, from the verified information only."
      }
    },
    {
      "n": 7,
      "ch": 3,
      "actor": "human",
      "min": 8,
      "what": {
        "ga": "Duine a sheiceálann le naoi seiceáil agus seiceáil Ghaeilge.",
        "en": "A human checks — nine checks plus the Irish checks."
      }
    },
    {
      "n": 8,
      "ch": 3,
      "actor": "human",
      "min": 5,
      "what": {
        "ga": "Dearadh: Canva nó pár. An téacs ceadaithe amháin.",
        "en": "Design: Canva or paper. Approved text only."
      }
    },
    {
      "n": 9,
      "ch": 3,
      "actor": "human",
      "min": 3,
      "what": {
        "ga": "An duine ainmnithe a cheadaíonn — nó ní cheadaíonn.",
        "en": "The named approver signs off — or does not."
      }
    }
  ],
  "WALL": [
    {
      "concern": {
        "ga": "Muinín agus cruinneas",
        "en": "Trust and accuracy"
      },
      "status": {
        "ga": "Freagartha inniu",
        "en": "Answered today"
      },
      "kind": "done"
    },
    {
      "concern": {
        "ga": "Príobháideacht agus rúndacht",
        "en": "Privacy and confidentiality"
      },
      "status": {
        "ga": "Freagartha inniu",
        "en": "Answered today"
      },
      "kind": "done"
    },
    {
      "concern": {
        "ga": "Rialacha agus cead",
        "en": "Rules and permission"
      },
      "status": {
        "ga": "I bhfoirm achoimre inniu. Tuilleadh: leathanach an Achta AI. Níl an t-eolas iomlán againn fós.",
        "en": "In outline today. More: the AI Act page. Not the full picture yet."
      },
      "kind": "partial"
    },
    {
      "concern": {
        "ga": "Obair agus poist",
        "en": "Work and jobs"
      },
      "status": {
        "ga": "Seisiún 4",
        "en": "Session 4"
      },
      "kind": "later"
    },
    {
      "concern": {
        "ga": "An Ghaeilge",
        "en": "The Irish language"
      },
      "status": {
        "ga": "Seisiún 3",
        "en": "Session 3"
      },
      "kind": "later"
    }
  ],
  "WORKFLOW": [
    {
      "id": "w1",
      "step": {
        "ga": "Tasc",
        "en": "Task"
      },
      "q": {
        "ga": "Cad é an tasc, i bhfocail shimplí, gan AI a lua?",
        "en": "What is the task, in plain words, without mentioning AI?"
      }
    },
    {
      "id": "w2",
      "step": {
        "ga": "Foinse",
        "en": "Source"
      },
      "q": {
        "ga": "Cad iad na fíricí agus na foinsí atá ar eolas agam cheana?",
        "en": "Which facts and sources do I already have?"
      }
    },
    {
      "id": "w3",
      "step": {
        "ga": "Prompt",
        "en": "Prompt"
      },
      "q": {
        "ga": "Ról, comhthéacs, tasc, srianta, aschur — agus: ná cum faisnéis.",
        "en": "Role, context, task, constraints, output — and: do not invent information."
      }
    },
    {
      "id": "w4",
      "step": {
        "ga": "Gin",
        "en": "Generate"
      },
      "q": {
        "ga": "Faigh dréacht. Ná stop ag an gcéad iarracht.",
        "en": "Get a draft. Do not stop at the first attempt."
      }
    },
    {
      "id": "w5",
      "step": {
        "ga": "Fíoraigh",
        "en": "Verify"
      },
      "q": {
        "ga": "Seiceáil fíricí, uimhreacha, ainmneacha agus Gaeilge.",
        "en": "Check facts, numbers, names and Irish."
      }
    },
    {
      "id": "w6",
      "step": {
        "ga": "Feabhsaigh",
        "en": "Improve"
      },
      "q": {
        "ga": "Inis dó cad a bhí mícheart agus cén fáth.",
        "en": "Tell it what was wrong and why."
      }
    },
    {
      "id": "w7",
      "step": {
        "ga": "Ceadú",
        "en": "Approve"
      },
      "q": {
        "ga": "Duine ainmnithe a cheadaíonn. Ní hé AI.",
        "en": "A named person approves. Not AI."
      }
    }
  ],
  "WORKFLOW_NOTE": {
    "ga": "Coinnigh an prompt a d’oibrigh.",
    "en": "Keep the prompt that worked."
  },
  "WORKFLOW_TASK": {
    "ga": "Roghnaigh tasc fíor amháin ó do sheachtain féin. Ainmnigh an duine a cheadaíonn.",
    "en": "Choose one real task from your own week. Name the person who approves."
  },
  "WORKSHOP_INTRO": {
    "title": {
      "ga": "Ó AI go hObair",
      "en": "From AI to work"
    },
    "line": {
      "ga": "AI mar chúntóir → AI mar athbhreithneoir → AI mar chomhoibrí cruthaitheach → AI mar chuid de shruth oibre.",
      "en": "AI as assistant → AI as reviewer → AI as creative collaborator → AI as part of a workflow."
    },
    "group": {
      "ga": "Grúpaí de thriúr. Cúig ghrúpa.",
      "en": "Groups of three."
    },
    "safety": {
      "ga": "Sampla ficseanúil amháin. Ná cuir faisnéis fhíor isteach in uirlis phoiblí AI.",
      "en": "One fictional example only. Do not put real information into a public AI tool."
    },
    "tools": {
      "ga": "Úsáid aon uirlis AI oiriúnach atá agat cheana. Ní gá cuntas nua. Gan rochtain? Oibrígí le rannpháirtí eile.",
      "en": "Use any suitable AI tool you already have. No new account needed. No access? Work with another participant."
    }
  }
} as const
